# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1rFL5AB98rQXdtpuAYJV_TVdZhn2G5r
"""

!pip install leafmap

import leafmap

#Английская версия яндекс карт
m0 = leafmap.Map(center=(40, -100), zoom=4, width=800, height=500)
url_0 = 'https://core-renderer-tiles.maps.yandex.net/tiles?l=map&v=26.03.19-0~b:260316072700~ib:26.03.20-1&x={x}&y={y}&z={z}&scale=1&lang=en_US&projection=web_mercator'
m0.remove_layer(m0.layers[0])
m0.add_tile_layer(url=url_0, name='Яндекс', attribution='Yandex')
m0

#Тема зелённая яндекс карт
m1 = leafmap.Map(center=(40, -100), zoom=4, width=800, height=500)
url_1 = 'https://core-renderer-tiles.maps.yandex.net/tiles?l=map&v=26.03.19-0~b:260316072700~ib:26.03.20-1&x={x}&y={y}&z={z}&scale=1&lang=ru_RU&projection=web_mercator&style=elements:geometry|stylers.hue:0A4500~elements:label.icon|stylers.hue:0A4500~elements:label.text.fill|stylers.color:0A4500'
m1.remove_layer(m1.layers[0])
m1.add_tile_layer(url=url_1, name='Яндекс', attribution='Yandex')
m1

#Подписи окрашены в Mangento яндекс карт
m2 = leafmap.Map(center=(40, -100), zoom=4, width=800, height=500)
url_2 = 'https://core-renderer-tiles.maps.yandex.net/tiles?l=map&v=26.03.19-0~b:260316072700~ib:26.03.20-1&x={x}&y={y}&z={z}&scale=1&lang=ru_RU&projection=web_mercator&style=tags.any:poi;transit_location|elements:label.text.fill|stylers.color:FF496C'
m2.remove_layer(m2.layers[0])
m2.add_tile_layer(url=url_2, name='Яндекс', attribution='Yandex')
m2

#Только значки магазинов окрашены в красный цвет яндекс карт
m4 = leafmap.Map(center=(40, -100), zoom=4, width=800, height=500)
url_4 = 'https://core-renderer-tiles.maps.yandex.net/tiles?l=map&v=26.03.19-0~b:260316072700~ib:26.03.20-1&x={x}&y={y}&z={z}&scale=1.5&lang=ru_RU&projection=web_mercator&style=tags.any:poi|tags.none:shopping|elements:label|stylers.visibility:off~tags.all:shopping|elements:label.text.fill|stylers.color:DD0000~tags:shopping|elements:label.icon|stylers.color:DD0000|stylers.scale:1.1'
m4.remove_layer(m4.layers[0])
m4.add_tile_layer(url=url_4, name='Яндекс', attribution='Yandex')
m4

#Моя карта важных зданий окрашены в красный цвет. Яндекс карт
m5 = leafmap.Map(center=(56, 37), zoom=8, width=800, height=500)
url_5 = 'https://core-renderer-tiles.maps.yandex.net/tiles?l=map&v=26.03.19-0~b:260316072700~ib:26.03.20-1&x={x}&y={y}&z={z}&scale=1.5&lang=ru_RU&theme=dark&apikey&projection=web_mercator&style=tags.any:poi|tags.none:major_landmark|elements:label|stylers.visibility:off~tags.all:major_landmark|elements:label.text.fill|stylers.color:DD0000~tags:major_landmark|elements:label.icon|stylers.color:DD0000|stylers.scale:1.1'
m5.remove_layer(m5.layers[0])
m5.add_tile_layer(url=url_5, name='Яндекс', attribution='Yandex')
m5